Vagrant.configure("2") do |config|

  # Jenkins VM
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/jammy64"
    jenkins.vm.hostname = "vm-jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.10"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Kubernetes Master
  config.vm.define "k8s-master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "vm-k8s-master"
    master.vm.network "private_network", ip: "192.168.56.11"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Kubernetes Worker
  config.vm.define "k8s-worker" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "vm-k8s-worker"
    worker.vm.network "private_network", ip: "192.168.56.12"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end
